django_todo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'))
]

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    # 详情页
    path('<int:id>', views.detail, name='detail'),
    # 完成时间
    path('<int:id>/finish', views.finish, name='finish'),
    # 完成
    path('<int:id>/cancel', views.cancel, name='cancel'),
    # 添加
    path('create/', views.create, name="create"),
]

todo/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta
import datetime


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

    def __str__(self):
        return self.username


class Todo(models.Model):

    content = models.CharField('内容', max_length=200)
    creat_time = models.DateTimeField('创建时间', default=timezone.now)
    status = models.BooleanField('状态', default=False)

    finish_time = models.DateTimeField('结束时间', auto_now=True)

    qid = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

todo/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.urls import reverse
from .models import Todo,User
from datetime import datetime


# Create your views here.
def index(request):
    x = Todo.objects.select_related().order_by('status', '-creat_time')
    content = {
        'x': x
    }
    return render(request, 'todo/index.html', content)


def detail(request, id):
    x = Todo.objects.get(pk=id)
    i = Todo.objects.all()
    context = {
        'x': x,
        'i': i
    }
    return render(request, 'todo/detail.html', context)


def finish(request, id):
    x = Todo.objects.get(pk=id)
    x.status = True
    x.finish_time = datetime.now()
    x.save()
    return HttpResponseRedirect(reverse('todo:index'))


def cancel(request, id):
    x = Todo.objects.get(pk=id)
    x.status = False
    x.save()
    return HttpResponseRedirect(reverse('todo:index'))


def create(request):
    content = request.POST["content"]
    x = Todo(content=content,
             creat_time=datetime.now(),
             qid_id=1
             )
    x.save()

    return HttpResponseRedirect(reverse('todo:index'))

templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'todo/css/bootstrap.css' %}">
  <title>详情页</title>

</head>
<body>
    <div>
      <table class="table table-striped">
        <tr>
          <td>内容</td>
          <td>发布时间</td>
          <td>完成时间</td>
          <td>状态</td>
        </tr>
        {% if  x.status == False %}
        <tr>
          <td>{{ x.content }}</td>
          <td>{{ x.creat_time }}</td>
          <td>{{ x.finish_time }}</td>
          <td>未完成</td>
        </tr>
        {% elif x.status == True %}
          <tr>
          <td>{{ x.content }}</td>
          <td>{{ x.creat_time }}</td>
          <td>{{ x.finish_time }}</td>
          <td>完成</td>
          </tr>
        {% else %}
            <li>列表为空</li>
        {% endif %}
      </table>
    </div>
    <div align="center">
          <a href="{% url 'todo:finish' x.id %}"><button type="button" class="btn btn-success navbar-btn" >完成</button></a>
        <a href="{% url 'todo:cancel' x.id %}">
        <button type="button" class="btn btn-success navbar-btn">取消</button></a>
    </div>
</body>
</html>

templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'todo/css/bootstrap.css' %}">
  <title>首页</title>

</head>
<body>
  <h1 align="center">todo</h1>
  <ul>
    {% for q in x %}
    <p align="center"><a href="{% url 'todo:detail' q.id %}"> 内容：{{ q.content }} 发布时间：{{ q.creat_time }} 状态：{{ q.status }}</a></p>
    {% empty %}
      <li>列表为空</li>
    {% endfor %}
  </ul>

  <div class="form-group-lg" align="center">

  <form action="{% url "todo:create"  %}" method="post">
    {% csrf_token %}
    <textarea rows="5" cols="50" placeholder="请输入待办事项" name="content"></textarea>
    <br>
    <button type="submit" class="btn btn-success btn-lg">添加</button>
  </form>
  </div>
</body>
</html>